import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  card: {
    width: "100%",
    maxWidth: 390,
    alignSelf: "center",
    backgroundColor: "#dce8d7",
    borderWidth: 1,
    borderColor: "rgba(37, 96, 29, 0.12)",
    borderRadius: 22,
    paddingHorizontal: 24,
    paddingVertical: 28,
    shadowColor: "#1f4d17",
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.12,
    shadowRadius: 20,
    elevation: 10,
    gap: 18,
  },
  title: {
    textAlign: "center",
    color: "#102c17",
    fontSize: 28,
    fontWeight: "900",
    lineHeight: 34,
  },
  subtitle: {
    textAlign: "center",
    color: "#314a37",
    fontSize: 16,
    lineHeight: 28,
    marginBottom: 8,
  },
  divider: {
    width: 96,
    height: 4,
    borderRadius: 999,
    alignSelf: "center",
    marginVertical: 2,
  },
  successBox: {
    backgroundColor: "#dbe5de",
    borderWidth: 1,
    borderColor: "#b7d3bf",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginBottom: 6,
  },
  successText: {
    color: "#314a37",
    fontWeight: "500",
    textAlign: "left",
    fontSize: 14,
    lineHeight: 20,
  },
  tokenFieldWrap: {
    gap: 6,
  },
  tokenLabel: {
    color: "#1e3a21",
    fontWeight: "800",
    fontSize: 14,
  },
  tokenInputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f6f6f6",
    borderWidth: 1,
    borderColor: "#b6cbb9",
    borderRadius: 8,
    paddingHorizontal: 12,
    minHeight: 52,
  },
  tokenInput: {
    flex: 1,
    color: "#1e293b",
    fontSize: 14,
    paddingVertical: 12,
  },
  tokenEyeButton: {
    marginLeft: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  tokenError: {
    color: "#b42318",
    fontSize: 12,
  },
});